import os
import sys
import argparse
import urllib.request
import xml.etree.ElementTree as ET
from urllib.parse import urlparse

# Template for project_qa.py (subclass)
PROJECT_QA_TEMPLATE = """from base_qa import BaseQA

class ProjectQA(BaseQA):
    \"\"\"
    Custom QA automation class generated for the project.
    Extend this class to write custom actions (like login, form fills).
    \"\"\"
    def __init__(self, base_url="{base_url}", out_dir="{out_dir}", is_mobile=False, viewport=None):
        super().__init__(base_url, out_dir, is_mobile, viewport)
"""

# Template for run_project.py (runner)
RUN_PROJECT_TEMPLATE = """# Playwright Visual QA Runner Script
# Generated by visual-qa CLI

import os
from project_qa import ProjectQA
from playwright.sync_api import sync_playwright

# 1. Initialize custom QA Configuration
qa = ProjectQA(
    base_url="{base_url}",
    out_dir="{out_dir}",
    is_mobile=False
)

# 2. Automated screenshots routes list
# WARNING: All-automatic detection might miss some pages. Edit this list as needed.
ROUTES = [
{routes_list}
]

print("🚀 Starting Visual QA regression test suite...")

with sync_playwright() as p:
    # Launch headless browser
    browser = p.chromium.launch(headless=True)
    ctx = qa.create_context(browser)
    page = ctx.new_page()

    for idx, route in enumerate(ROUTES):
        # Handle dynamic routing placeholder warning
        if ":" in route or "TODO" in route:
            print(f"  [Jumped] Dynamic routing placeholder found: {{route}}. Please replace with valid data manually.")
            continue

        target_url = qa.base_url + route
        print(f"  → Navigating: {{target_url}}")
        try:
            page.goto(target_url, wait_until="networkidle", timeout=15000)
        except Exception as e:
            # Fallback if networkidle timeouts
            try:
                page.goto(target_url, wait_until="domcontentloaded", timeout=10000)
            except Exception as ex:
                print(f"  ⚠️ Navigation failed for {{route}}: {{ex}}")
                continue

        # Intelligent anti-shake wait & capture
        qa.wait(page, 1500)
        
        # Format filename cleanly
        safe_name = f"{{idx:02d}}_{{route.replace('/', '_').strip('_') or 'home'}}"
        qa.shot(page, safe_name)

    ctx.close()
    browser.close()

# 3. Compile report
qa.list_results()
"""

def scan_nextjs(cwd):
    """
    Scans a Next.js directory tree (App Router & Pages Router) and yields routes.
    """
    routes = []
    
    # 1. App Router check (prioritize src/app, then app)
    app_dir = os.path.join(cwd, "src", "app")
    if not os.path.exists(app_dir):
        app_dir = os.path.join(cwd, "app")
        
    if os.path.exists(app_dir):
        for root, _, files in os.walk(app_dir):
            for file in files:
                if file in ["page.tsx", "page.jsx", "page.js"]:
                    rel_path = os.path.relpath(root, app_dir)
                    if rel_path == ".":
                        routes.append("/")
                    else:
                        route = "/" + rel_path.replace("\\", "/")
                        # Format Next.js dynamic routing, e.g. [id] -> :id
                        route = route.replace("[", ":").replace("]", "")
                        routes.append(route)

    # 2. Pages Router check (src/pages, then pages)
    pages_dir = os.path.join(cwd, "src", "pages")
    if not os.path.exists(pages_dir):
        pages_dir = os.path.join(cwd, "pages")
        
    if os.path.exists(pages_dir):
        for root, _, files in os.walk(pages_dir):
            for file in files:
                if file.endswith((".tsx", ".jsx", ".js")) and not file.startswith(("_", "api")):
                    rel_path = os.path.relpath(os.path.join(root, file), pages_dir)
                    # Strip extensions
                    base_route, _ = os.path.splitext(rel_path)
                    base_route = base_route.replace("\\", "/")
                    
                    if base_route == "index":
                        routes.append("/")
                    elif base_route.endswith("/index"):
                        routes.append("/" + base_route[:-6])
                    else:
                        route = "/" + base_route
                        route = route.replace("[", ":").replace("]", "")
                        routes.append(route)
                        
    # Deduplicate and sort
    return sorted(list(set(routes)))

def fetch_sitemap_routes(sitemap_url, target_base_url):
    """
    Fetches sitemap XML and extracts relative paths.
    """
    print(f"📡 Fetching sitemap: {sitemap_url} ...")
    try:
        req = urllib.request.Request(
            sitemap_url, 
            headers={'User-Agent': 'Mozilla/5.0 (Playwright Visual QA CLI)'}
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            xml_data = response.read()
    except Exception as e:
        print(f"❌ Failed to fetch sitemap: {e}")
        sys.exit(1)

    try:
        root = ET.fromstring(xml_data)
    except Exception as e:
        print(f"❌ Failed to parse sitemap XML: {e}")
        sys.exit(1)

    routes = []
    for elem in root.iter():
        if elem.tag.endswith('loc'):
            url = elem.text.strip() if elem.text else ""
            if url:
                parsed_url = urlparse(url)
                # Extract path + query + fragment
                path = parsed_url.path
                if parsed_url.query:
                    path += "?" + parsed_url.query
                routes.append(path or "/")
                
    # Deduplicate and sort
    return sorted(list(set(routes)))

def cmd_init(args):
    cwd = os.getcwd()
    routes = []
    framework = args.framework
    
    # 1. Sitemap Mode takes precedence
    if args.sitemap:
        print(f"🔍 Mode: Sitemap URL Scanner")
        routes = fetch_sitemap_routes(args.sitemap, args.url)
    # 2. Source Code Scan Mode
    else:
        print(f"🔍 Mode: Local Source Code Scanner")
        # Framework auto-detect
        if not framework:
            if os.path.exists(os.path.join(cwd, "next.config.js")) or os.path.exists(os.path.join(cwd, "next.config.ts")):
                framework = "nextjs"
                print("  ✓ Detected Next.js framework configuration.")
            else:
                framework = "generic"
                
        if framework == "nextjs":
            routes = scan_nextjs(cwd)
            if not routes:
                print("  ⚠️ No page routes discovered under Next.js directories.")
        else:
            print("  ⚠️ No framework matched or generic mode specified.")
            print("  👉 Note: Pure-automated scanner might be incomplete. Generating base setup with placeholder...")
            routes = ["/", "/about", "/contact", "/dashboard"]

    # 3. Render and save scripts
    routes_list_str = "\n".join(f'    "{r}",' for r in routes)
    
    # Output project_qa.py
    project_qa_content = PROJECT_QA_TEMPLATE.format(
        base_url=args.url,
        out_dir=args.out
    )
    project_qa_path = os.path.join(cwd, "project_qa.py")
    with open(project_qa_path, "w", encoding="utf-8") as f:
        f.write(project_qa_content)
    print(f"  ✓ Scaffolded subclass: {project_qa_path}")
    
    # Output run_project.py
    run_project_content = RUN_PROJECT_TEMPLATE.format(
        base_url=args.url,
        out_dir=args.out,
        routes_list=routes_list_str
    )
    run_project_path = os.path.join(cwd, "run_project.py")
    with open(run_project_path, "w", encoding="utf-8") as f:
        f.write(run_project_content)
    print(f"  ✓ Scaffolded runner:   {run_project_path}")
    
    print("\n🎉 Success! Scaffold completed.")
    print("👉 Edit 'run_project.py' to adjust your route list.")
    print("👉 Run testing suite by executing: python3 run_project.py")

def main():
    parser = argparse.ArgumentParser(
        description="Playwright Visual QA Scaffold CLI tool.",
        prog="visual-qa"
    )
    
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # init command
    init_parser = subparsers.add_parser("init", help="Initialize a visual QA automation project templates in current workspace.")
    init_parser.add_argument("-u", "--url", default="http://localhost:3000", help="Base URL of your web app (default: http://localhost:3000)")
    init_parser.add_argument("-o", "--out", default="./qa-screenshots", help="Directory where screenshots will be saved (default: ./qa-screenshots)")
    init_parser.add_argument("-f", "--framework", choices=["nextjs", "generic"], help="Force specify framework rules. Auto-detects if omitted.")
    init_parser.add_argument("-s", "--sitemap", help="Provide a Sitemap URL (e.g. http://localhost:3000/sitemap.xml) to fetch routes from.")
    
    args = parser.parse_args()
    
    if args.command == "init":
        cmd_init(args)

if __name__ == "__main__":
    main()
